# Generated by Django 5.2.7 on 2025-10-31 15:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubjectData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_subject_data', models.CharField(max_length=255)),
                ('consent_status', models.BooleanField()),
                ('consent_given_date', models.DateField()),
                ('consent_revoked_date', models.DateField(blank=True, null=True)),
                ('consent_given_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sensor_data', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('DATA_PROVIDER', 'Data Subject/Data Provider'), ('DATACONTROLLER_PROCESSOR', 'Data Contact/Data Processor')], default='DATA_PROVIDER', max_length=100)),
                ('mongo_id', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRequest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('consent_request_form_title', models.CharField(default='Consent Request Form', max_length=455)),
                ('general_ontology', models.CharField(max_length=255)),
                ('domain_ontology', models.CharField(max_length=255)),
                ('schema_ontology', models.CharField(max_length=255)),
                ('consent_data', models.CharField(max_length=255)),
                ('consent_purpose', models.CharField(max_length=255)),
                ('consent_operations', models.JSONField(default='{}')),
                ('consent_date_start', models.DateField()),
                ('consent_date_end', models.DateField()),
                ('additional_requests', models.JSONField(default='{}')),
                ('consent_request_sent_status', models.CharField(choices=[('SENT', 'Sent'), ('CREATED', 'Created')], default='CREATED', max_length=55)),
                ('consent_form_delete_status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ManyToManyField(related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('consent_requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_requested_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_request_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRequestFormSendToUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('consent_answer_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('RESPONDED', 'Responded'), ('REVOKED', 'Revoked')], default='REQUESTED', max_length=100)),
                ('consent_given_status', models.CharField(default='Requested', max_length=100)),
                ('additional_constraints', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_request_form_sent_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_request_form_sent_to', to=settings.AUTH_USER_MODEL)),
                ('consent_requestform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_request', to='custom_accounts.consentrequest')),
                ('sent_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_request_form_sent_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRequestFormResponseODRL',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('odrl_consent_additional_constraints', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consented_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consented_given_by_user', to=settings.AUTH_USER_MODEL)),
                ('data_controller_processor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_requested_by_controller_processor', to=settings.AUTH_USER_MODEL)),
                ('consentrequestsendtouserformid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_request_sent_to_user_form', to='custom_accounts.consentrequestformsendtouser')),
            ],
        ),
        migrations.CreateModel(
            name='OntologyUpload',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('file', models.FileField(upload_to='ontology/')),
                ('ontology_type', models.CharField(default='DATA_CONTEXT', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileuploadsby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
